modLoader="javafml"
loaderVersion = "[4,)"
license="GNU LGPL 3.0"
issueTrackerURL="https://Anthony/sol_valheim/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${display_name}"
authors = "Me!"
description = '''
'''
logoFile = "icon.png"

[[mixins]]
config = "sol_valheim.mixins.json"

[[mixins]]
config = "sol_valheim-common.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
